name: Build Android App Bundle Smart

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Unzip project code
        run: |
          unzip -o direct_chat_unsaved.zip -d extracted_project
          PUBSPEC_PATH=$(find extracted_project -name "pubspec.yaml" -type f | head -n 1)
          PROJECT_DIR=$(dirname "$PUBSPEC_PATH")
          echo "Found project at: $PROJECT_DIR"
          cp -rn $PROJECT_DIR/* .

      - name: Make Gradlew Executable
        run: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle --debug --android-skip-build-dependency-validation

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/debug/app-debug.aab
